services:
  - type: web
    name: api-rne-elus
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn api:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: RNE_API_KEY
        value: 241217-eliana-201724-suvannah
